version: '3.5'
services:
  peercoind:
    image: peercoin/peercoind:latest
    restart: always
    environment:
      - RPC_USER=USER
      - RPC_PASSWORD=PASS
    volumes:
      - type: bind
        source: ./.peercoin
        target: /data
    command:
      -rpcbind=0.0.0.0
      -nominting
      -printtoconsole
  electrumx:
    image: peercoin/electrumx:latest
    environment:
      - DAEMON_URL=USER:PASS@peercoind
      - COIN=Peercoin
      - DB_DIRECTORY=/data
      - CACHE_MB=400
      - SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
      - DONATION_ADDRESS=p92W3t7YkKfQEPDb7cG9jQ6iMh7cpKLvwK 
    volumes:
      - type: bind
        source: .electrum
        target: /data
    ports:
      - "50001:50001" # comment out to disable TCP port (plaintext)
      - "50002:50002"
      - "50004:50004"
      - "8000:8000"
    restart: always
    depends_on:
      - peercoind
